# Create a Replica Set of 5 Pods with the Elements image

kind: ReplicaSet
apiVersion: apps/v1
metadata:
  name: myrstesting
  labels:
    app: rsexample
  namespace: default
  annotations:
    CREATEDBY: "Mubashir Ali"
spec:
  replicas: 5
  selector:
    matchLabels:
      type: backend
      env: development
    matchExpressions:
    - key: type
      operator: In
      values:
      - backend 
    - key: env
      operator: In
      values:
      - development
  template:
    metadata:
      labels:
        type: backend
        env: development
    spec:
      volumes:
      - name: shared-dir
        emptyDir: {}
      containers:
      - name: container1
        image: mubashirimtiaz/wave:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        volumeMounts:
        - name: shared-dir
          mountPath: /tmp/vol-example
        livenessProbe: 
          httpGet: 
            port: 80
            path: /
        readinessProbe: 
          httpGet: 
            port: 80
            path: /
      - name: container2
        image: aamirpinger/logfile_nodejs
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: shared-dir
          mountPath: /data
        livenessProbe:
          exec: 
            command:
            - ls
        readinessProbe:
          exec: 
            command:
            - ls

